---
- name: Deploy adguard home container
  community.docker.docker_container:
    name: adguard
    image: adguard/adguardhome
    restart_policy: unless-stopped
    networks:
      - name: homelab
    ports:
      - "192.168.1.10:53:53/tcp"
      - "192.168.1.10:53:53/udp"
    volumes:
      - "{{ docker_dir }}/adguard_home/work:/opt/adguardhome/work"
      - "{{ docker_dir }}/adguard_home/conf:/opt/adguardhome/conf"
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.entrypoints: "http"
      traefik.http.routers.adguard.rule: "Host(`adguard.{{ domain }}`)"
      traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.adguard.middlewares: "adguard-https-redirect"
      traefik.http.routers.adguard-secure.entrypoints: "https"
      traefik.http.routers.adguard-secure.rule: "Host(`adguard.{{ domain }}`)"
      traefik.http.routers.adguard-secure.tls: "true"
      traefik.http.routers.adguard-secure.service: "adguard"
      traefik.http.services.adguard.loadbalancer.server.port: "3000"
      traefik.docker.network: "homelab"
