---
- name: Deploy beszel container
  community.docker.docker_container:
    name: beszel
    image: henrygd/beszel
    restart_policy: unless-stopped
    networks:
      - name: homelab
    volumes:
      - "{{ docker_dir }}/beszel/:/beszel_data"
      - "{{ docker_dir }}/beszel/socket/:/beszel_socket"
    labels:
      traefik.enable: "true"
      traefik.http.routers.beszel.entrypoints: "http"
      traefik.http.routers.beszel.rule: "Host(`beszel.{{ domain }}`)"
      traefik.http.middlewares.beszel-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.beszel.middlewares: "beszel-https-redirect"
      traefik.http.routers.beszel-secure.entrypoints: "https"
      traefik.http.routers.beszel-secure.rule: "Host(`beszel.{{ domain }}`)"
      traefik.http.routers.beszel-secure.tls: "true"
      traefik.http.routers.beszel-secure.service: "beszel"
      traefik.http.services.beszel.loadbalancer.server.port: "8090"
      traefik.docker.network: "homelab"

- name: Deploy beszel-agent container
  community.docker.docker_container:
    name: beszel_agent
    image: henrygd/beszel-agent
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ docker_dir }}/beszel/socket/:/beszel_socket"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      PORT: "45876"
      KEY: "{{ beszel_agent_key }}"
