---
- name: Deploy codeserver container
  community.docker.docker_container:
    name: codeserver
    image: lscr.io/linuxserver/code-server
    restart_policy: unless-stopped
    networks:
      - name: homelab
    volumes:
      - "/home/{{ username }}/:/home/{{ username }}"
      - "{{ docker_dir }}/code_server/config:/config"
    env:
      PGID: "{{ pgid }}"
      PUID: "{{ puid }}"
      PASSWORD: "{{ codeserver_password }}"
      SUDO_PASSWORD: "{{ codeserver_password }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.code.entrypoints: "http"
      traefik.http.routers.code.rule: "Host(`code.{{ domain }}`)"
      traefik.http.middlewares.code-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.code.middlewares: "code-https-redirect"
      traefik.http.routers.code-secure.entrypoints: "https"
      traefik.http.routers.code-secure.rule: "Host(`code.{{ domain }}`)"
      traefik.http.routers.code-secure.tls: "true"
      traefik.http.routers.code-secure.service: "code"
      traefik.http.services.code.loadbalancer.server.port: "8443"
      traefik.docker.network: "homelab"
