---
- name: Create frigate config file
  ansible.builtin.copy:
    dest: "{{ docker_dir }}/frigate/config.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
    content: |
      tls:
        enabled: False
      mqtt:
        enabled: False

      detectors:
        cpu:
          type: cpu

      snapshots:
        enabled: True
        bounding_box: True
        retain:
          default: 7

      cameras:
        front:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://admin:{{ frigate_rtsp_password }}:@192.168.1.4:5543/live/channel1
                roles:
                  - detect
              - path: rtsp://admin:{{ frigate_rtsp_password }}:@192.168.1.4:5543/live/channel0
                roles:
                  - record
          detect:
            enabled: True
          record:
            enabled: True
            retain: 
              days: 7
              mode: active_objects
            alerts:
              retain:
                days: 7
            detections:
              retain:
                days: 7
              pre_capture: 10
              post_capture: 10
        back:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://admin:{{ frigate_rtsp_password }}:@192.168.1.3:5543/live/channel1
                roles:
                  - detect
              - path: rtsp://admin:{{ frigate_rtsp_password }}:@192.168.1.3:5543/live/channel0
                roles:
                  - record
          detect:
            enabled: True
          record:
            enabled: True
            retain: 
              days: 7
              mode: active_objects
            alerts:
              retain:
                days: 7
            detections:
              retain:
                days: 7
              pre_capture: 10
              post_capture: 10

- name: Deploy frigate container
  community.docker.docker_container:
    name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart_policy: unless-stopped
    networks:
      - name: homelab
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir}}/frigate/:/config/"
      - "{{ data_dir }}/frigate/media:/media/frigate"
    tmpfs:
      - "/tmp/cache:size=1000000000"
    shm_size: 512m
    env:
      FRIGATE_RTSP_PASSWORD: "{{ frigate_rtsp_password }}:"
    ports:
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    labels:
      traefik.enable: "true"
      traefik.http.routers.frigate.entrypoints: "http"
      traefik.http.routers.frigate.rule: "Host(`frigate.{{ domain }}`)"
      traefik.http.middlewares.frigate-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.frigate.middlewares: "frigate-https-redirect"
      traefik.http.routers.frigate-secure.entrypoints: "https"
      traefik.http.routers.frigate-secure.rule: "Host(`frigate.{{ domain }}`)"
      traefik.http.routers.frigate-secure.tls: "true"
      traefik.http.routers.frigate-secure.service: "frigate"
      traefik.http.services.frigate.loadbalancer.server.port: "8971"
      traefik.docker.network: "homelab"
