---
- name: Deploy hoader web container
  community.docker.docker_container:
    name: hoarder_web
    image: ghcr.io/hoarder-app/hoarder:release
    restart_policy: unless-stopped
    networks:
      - name: homelab
    volumes:
      - "{{ docker_dir }}/hoarder:/data"
    env:
      NEXTAUTH_SECRET: "{{ hoarder_nextauth_secret }}"
      MEILI_MASTER_KEY: "{{ hoarder_meili_master_key }}"
      NEXTAUTH_URL: "http://hoarder.{{ domain }}"
      MEILI_ADDR: http://hoarder_meilisearch:7700
      BROWSER_WEB_URL: http://hoarder_chrome:9222
      DATA_DIR: /data
    labels:
      traefik.enable: "true"
      traefik.http.routers.hoarder.entrypoints: "http"
      traefik.http.routers.hoarder.rule: "Host(`hoarder.{{ domain }}`)"
      traefik.http.middlewares.hoarder-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.hoarder.middlewares: "hoarder-https-redirect"
      traefik.http.routers.hoarder-secure.entrypoints: "https"
      traefik.http.routers.hoarder-secure.rule: "Host(`hoarder.{{ domain }}`)"
      traefik.http.routers.hoarder-secure.tls: "true"
      traefik.http.routers.hoarder-secure.service: "hoarder"
      traefik.http.services.hoarder.loadbalancer.server.port: "3000"
      traefik.docker.network: "homelab"

- name: Deploy hoarder chrome container
  community.docker.docker_container:
    name: hoarder_chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart_policy: unless-stopped
    networks:
      - name: homelab
    command:
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=9222"
      - "--hide-scrollbars"

- name: Deploy meilisearch container
  community.docker.docker_container:
    name: hoarder_meilisearch
    image: getmeili/meilisearch:v1.11.1
    restart_policy: unless-stopped
    networks:
      - name: homelab
    env:
      MEILI_NO_ANALYTICS: "true"
      NEXTAUTH_SECRET: "{{ hoarder_nextauth_secret }}"
      MEILI_MASTER_KEY: "{{ hoarder_meili_master_key }}"
      NEXTAUTH_URL: "http://hoarder.{{ domain }}"
    volumes:
      - "{{ docker_dir }}/hoarder/meilisearch:/meili_data"
