---
- name: Deploy jellyseerr container
  community.docker.docker_container:
    name: jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr
    restart_policy: unless-stopped
    dns_servers: "1.1.1.1"
    env:
      TZ: "{{ timezone }}"
      FORCE_IPV4_FIRST: "true"
    volumes:
      - "{{ docker_dir }}/jellyseerr/config:/app/config"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyseerr.entrypoints: "http"
      traefik.http.routers.jellyseerr.rule: "Host(`jellyseerr.{{ domain }}`)"
      traefik.http.middlewares.jellyseerr-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.jellyseerr.middlewares: "jellyseerr-https-redirect"
      traefik.http.routers.jellyseerr-secure.entrypoints: "https"
      traefik.http.routers.jellyseerr-secure.rule: "Host(`jellyseerr.{{ domain }}`)"
      traefik.http.routers.jellyseerr-secure.tls: "true"
      traefik.http.routers.jellyseerr-secure.service: "jellyseerr"
      traefik.http.services.jellyseerr.loadbalancer.server.port: "5055"
      traefik.docker.network: "homelab"
