---
- name: Deploy portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    restart_policy: unless-stopped
    networks:
      - name: homelab
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/portainer/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    security_opts:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ domain }}`)"
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.portainer.middlewares: "portainer-https-redirect"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`portainer.{{ domain }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.docker.network: "homelab"
