---
- name: Deploy radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr
    restart_policy: unless-stopped
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/radarr/config:/config"
      - "{{ data_dir }}:/data"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.entrypoints: "http"
      traefik.http.routers.radarr.rule: "Host(`radarr.{{ domain }}`)"
      traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.radarr.middlewares: "radarr-https-redirect"
      traefik.http.routers.radarr-secure.entrypoints: "https"
      traefik.http.routers.radarr-secure.rule: "Host(`radarr.{{ domain }}`)"
      traefik.http.routers.radarr-secure.tls: "true"
      traefik.http.routers.radarr-secure.service: "radarr"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
      traefik.docker.network: "homelab"
