---
- name: Deploy vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server
    restart_policy: unless-stopped
    networks:
      - name: homelab
    volumes:
      - "{{ docker_dir }}/vaultwarden/data:/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vault.entrypoints: "http"
      traefik.http.routers.vault.rule: "Host(`vault.{{ domain }}`)"
      traefik.http.middlewares.vault-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.vault.middlewares: "vault-https-redirect"
      traefik.http.routers.vault-secure.entrypoints: "https"
      traefik.http.routers.vault-secure.rule: "Host(`vault.{{ domain }}`)"
      traefik.http.routers.vault-secure.tls: "true"
      traefik.http.routers.vault-secure.service: "vault"
      traefik.http.services.vault.loadbalancer.server.port: "80"
      traefik.docker.network: "homelab"
