---
- name: Deploy watchetower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    restart_policy: unless-stopped
    env:
      WATCHTOWER_CLEANUP: "true"
    networks:
      - name: homelab
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
